### ISSUE TITLE
Access control not enforced

### ISSUE THREAD

**Issue by 74monkeys** [strongloop/loopback-example-access-control#2]
I got the app up and running and then request the transactions from the test data user (1) using curl - so I am not passing a token, so I am not authenticated.
It happily returns all the transaction, which it shouldn't

$ curl http://0.0.0.0:4000/api/users/1/transactions
[
  {
    "id": 1,
    "userId": 1,
    "accountId": 1,
    "pos": "Gas and Test",
    "credit": 8283.81,
    "time": "2013-01-12T13:52:23.826Z"
  },
  {
    "id": 2,
    "userId": 1,
    "accountId": 1,
    "pos": "Jasmine Tea",
    "debit": 236.76,
    "time": "2013-03-09T06:35:51.862Z"
  },
...

**Comment by crandmck** [comment]
As https://github.com/strongloop/loopback/issues/115 has been closed, I'm going to close this as well.
