### ISSUE TITLE
Dump automigrate/autoupdate SQL commands

### ISSUE THREAD

**Issue by xinshouke** [strongloop/loopback-example-access-control#22]
I found these below models were stored in database:
"user","accessToken","bank", "account" "transaction", "alert"  
Would you like to share the SQL to create these tables for the models in database please?

**Comment by bajtos** [comment]
I check the sources. It's possible to get the SQL commands from a debug log (`DEBUG loopback:connector:* node myapp`), but that's not suitable for programatic consumption.

I'm relabelling this issue as a feature request.

**Comment by acrodrig** [comment]
Hi, I would like to know if this is being worked on. If it is not, is it possible for someone to give me directions on how to make the contribution? Thanks.

**Comment by superkhau** [comment]
You can make a contribution by submitting a pull request with your changes: https://help.github.com/articles/about-pull-requests/ and https://github.com/strongloop/loopback-contributor-docs and https://github.com/strongloop/loopback/wiki/Contributing-code may help.

**Comment by acrodrig** [comment]
@superkhau thanks. I did take a look at those documents. I was more interested in pointers (technical guidance) to the modules to study and ideas about how to change the code from the person who wrote it. I presume there are a couple of right ways to it and zillion wrong ones.  Cheers.

**Comment by superkhau** [comment]
@acrodrig I wrote the code for this module. Which part of the code are you interested in? With regards to dumping SQL statements in automigrate/autoupdate, you'll have to start digging into that feature at https://github.com/strongloop/loopback-datasource-juggler and the corresonding connector (this example uses the in-memory connector at https://github.com/strongloop/loopback-datasource-juggler/blob/master/lib/connectors/memory.js).

**Comment by acrodrig** [comment]
@superkhau I will look into the module you pointed me to. I did some autoupdate with `DEBUG` turned on and it is outputting some lines prefixed `SQL`, so I will look for that and then try to have a flag that prints the SQL instead of executing it. Does that seems like the right approach?

Question: your mention the memory connector. I presume there is no SQL commands involved in that connector. Why you bought it up?

**Comment by superkhau** [comment]
>I will look into the module you pointed me to. I did some autoupdate with DEBUG turned on and it is outputting some lines prefixed SQL, so I will look for that and then try to have a flag that prints the SQL instead of executing it. Does that seems like the right approach?

Yeah, that sounds reasonable. A `dry-run` flag and outputing to console should be fine. Submit a PR and we can discuss more there.

>Question: your mention the memory connector. I presume there is no SQL commands involved in that connector. Why you bought it up?

Nah, there are no commands there but I mean this example uses the memory connector (so DEBUG wouldn't bring up any SQL statements). You'll have to replace https://github.com/strongloop/loopback-example-access-control/blob/master/server/datasources.json#L4 with an actual SQL connector such as loopback-connector-mysql if you want to see statements related to this example.
