### ISSUE TITLE
Dynamic ACL and Other Principal Types

### ISSUE THREAD

**Issue by ritch** [strongloop/loopback-example-access-control#31]
- We need to showcase examples of access controls that apply to specific model instances (data).
- We need to add some access controls that use other principal types (beyond ROLE).

@raymondfeng can you come up with some examples that would make sense for this repo example?

This is an excerpt from a comment you made in confluence a while back:

```
Use cases:
Authenticate client applications, users, and/or devices  to identify who (which  principals) are calling the APIs
Personalization (use the established principals to personalize the response)
Protection (check the established principals against access control lists to protect sensitive information)
Authorize access to protected resources against those who makes the request
```

**Comment by jorgeramos** [comment]
Are there any examples of ACLs using APP principalType ?

**Comment by AlmaasAre** [comment]
:+1:

**Comment by vukasin0** [comment]
I'm looking across documentation and I wasn't able to find object level acl.

What I mean under "object level acl":

    for this object(model instance) {_id: "30ba61cb-7f82-46fa-a621-d5f84eeac07f" } those users has access [{_id: "346d01ca-ffad-4f4c-a97c-ae79093203c4", role: "editor"}, ....] 
    
and aggregation view too - like:

    this user {_id: "346d01ca-ffad-4f4c-a97c-ae79093203c4" } has access to those objects [{_id: "30ba61cb-7f82-46fa-a621-d5f84eeac07f", role: "editor"}, ....]

@ritch is it possible by current ACL implementation as your comment kinda pointing on that ?

**Comment by JonathanSilva** [comment]
Hey @vukasin0 
you found any way to make "object level acl"?

**Comment by vukasin0** [comment]
@JonathanSilva unfortunately I didn't have time to work on this but definitely it leads us to custom development :)

**Comment by Sandy1088** [comment]
Hello All,

I have a model Users and 2 remote methods i.e. Download and Upload......I want certain users to have access to Download method and not Upload.

How can I set a user as admin and allow him to access a method and others as user and deny them access?

Also I ran SQL profiler but was unable to understand how loopback checks ACL.

Please help

**Comment by Sandy1088** [comment]
Just for brainStorming 


realm | username | password| id 
------------ | -------------|------------|--------
1 | Admin1 | password | 1

id | principalType | principalId | roleId 
------------ | -------------|------------|--------
1 | Admin | 0 | 1 |

id | name | description
------------ | -------------|------------
1 | Admin | Admin

model | property | accesstype | permissions | principalType | principalId
------------ | -------------|------------|--------|----------|-----------|-----------
Users | Download | EXECUTE | ALLOW | ADMIN | 1 | 1

This how my ACL looks like when persisted .....but still does not work as expected

**Comment by dan-h-ch** [comment]
+1 👍 👍 👍 This much needed
