### ISSUE TITLE
No Ionic example?

### ISSUE THREAD

**Issue by belibasakis** [strongloop/loopback-example-access-control#39]
Relating to this blog post http://strongloop.com/strongblog/angular-js-sdk-loopbac/
should't the example look something like this http://strongloop.com/wp-content/uploads/2014/02/Screen-Shot-2014-02-20-at-8.36.49-AM.png and use Ionic for the frontend?

"Our example project looopback-example-access-control is a good example of leveraging the power of LoopBack AngularJS SDK and the Ionic Framework to build a sleek mobile web app."

**Comment by arulmanickam** [comment]
when i try in mobile can`t access url from it ?
