### ISSUE TITLE
/users/:id/projects still need authorization even I gave "admin" access token

### ISSUE THREAD

**Issue by hellowin** [strongloop/loopback-example-access-control#41]
I did:
1. Open `API Explorer`
2. Login as `Bob` (admin)
3. Put `access_token` on top of `API Explorer`
4. Try open `/users/1/projects` and it still need and authorization
5. I tried login with `John` (owner), the problem still exist

Why is that happen?

I also has same problem with my own project that I "clone" from this example.

**Comment by andrest** [comment]
Similar thing with GET /api/projects/list-projects

Unauthorized for guest, authenticated, owner and admin.
