### ISSUE TITLE
how to remove/backout a relation?

### ISSUE THREAD

**Issue by Radu3000** [strongloop/loopback-example-access-control#51]
While going through the tutorial I have incorrectly specified a name for the relation - should be "members" instead of "users".

- How do I undo the above?

C:\Projects\StrongLoop\loopback-example-access-control>slc loopback:relation
? Select the model to create the relationship from: team
? Relation type: has many
? Choose a model to create a relationship with: user
? Enter the property name for the relation: users
? Optionally enter a custom foreign key:

**Comment by superkhau** [comment]
You have to manually empty out the `acl` property (make it an empty array) in `/common/model/your-model.json`.

**Comment by superkhau** [comment]
Has the issue been resolved? Can I close it?

**Comment by superkhau** [comment]
For future reference, please post questions to https://groups.google.com/forum/#!forum/loopbackjs. See https://github.com/strongloop/loopback/wiki/Reporting-issues#question for more details.
