### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by Radu3000** [strongloop/loopback-example-access-control#52]
https://github.com/strongloop/loopback-example-access-control/blob/master/server/common/project.json
referenced in:
Note, you have to manually change READ to EXECUTE in project.json for the listProjects endpoint to work properly.

**Comment by KloeverGz** [comment]
How the fuck do I do this shit

**Comment by superkhau** [comment]
Actually, that note isn't relevant anymore. Removed from the readme. Thanks for the report!
