### ISSUE TITLE
Cannot find module 'body-parser'

### ISSUE THREAD

**Issue by Radu3000** [strongloop/loopback-example-access-control#53]
trying to do the tutorial manually and getting the same error even if i download the master:

C:\Projects\StrongLoop\loopback-example-access-control-master>slc run
INFO strong-agent API key not found, StrongOps dashboard reporting disabled.
Generate configuration with:
    npm install -g strongloop
    slc strongops
See http://docs.strongloop.com/strong-agent for more information.
supervisor running without clustering (unsupervised)

module.js:340
    throw err;
    ^
Error: Cannot find module 'body-parser'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (C:\Projects\StrongLoop\loopback-example-access-control-master\server\serv
er.js:1:80)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Object.<anonymous> (C:\Users\nbdn7o6\AppData\Roaming\npm\node_modules\strongloop\node_modules
\strong-supervisor\bin\sl-run.js:40:19)

**Comment by OwenBrotherwood** [comment]
@Radu3000 
Did you use the command: npm install in the directory that contains the example?

If you have not used, or understood the need for npm install you need some more general knowledge of the processes involed in running npm install that reads the package.json in order that a npm_modules directory is created that contains the required modules.

@superkhau 
I have just used the example today with no problems on a window 8.1 platform

**Comment by Radu3000** [comment]
i did an npm -g install 
isn't that sufficient?

**Comment by OwenBrotherwood** [comment]
npm install
slc run

**Comment by superkhau** [comment]
@OwenBrotherwood Thanks for looking. I just tried out the example and it's working fine for me too.

@Radu3000 `npm -g install` won't do it. Please consult the NPM documentation on how install works. You need to run `npm install` WITHOUT `-g` in the project root.

**Comment by superkhau** [comment]
@Radu3000 Also if you look at the README instructions, it clearly says:

```
git clone https://github.com/strongloop/loopback-example-access-control
cd loopback-example-access-control
npm install
node .
```

Reopen if you are still having issues.
