### ISSUE TITLE
[question] followed tutorial, localhost:3000 doesn't render index.ejs?

### ISSUE THREAD

**Issue by raibutera** [strongloop/loopback-example-access-control#57]
I've created a repo of my version of the example app @ [github/raibutera/try-loopback-access-control](https://github.com/raibutera/try-loopback-access-control)

as you can see, running node . in that project and opening a browser to localhost:3000 does not render index.ejs, but instead something akin to this:

```
{
  "started": "2015-05-06T05:50:04.230Z",
  "uptime": 39.764
}
```

has anyone else had a similar issue?

**Comment by superkhau** [comment]
You need to remove `root.js` from `server/boot` in your project. This tutorial uses an older version of LoopBack where you didn't have to do this manually.
