### ISSUE TITLE
Testing dynamic roles

### ISSUE THREAD

**Issue by teone** [strongloop/loopback-example-access-control#61]
Hi everybody,

as per my understandings the `Role.registerResolver` callback is triggered only if someone try to access a route where this role is used in the Acl.

I'm wondering which is the best way to write test for dynamic roles, as now I found out two ways:
- using [loopback-testing](https://github.com/strongloop/loopback-testing) to perform e2e test on protected routes
- perform unit tests on the `Role.registerResolver` callback

Any suggestion?

**Comment by richardpringle** [comment]
Hey @teone, sorry about the delayed response to your issue but we're actually reserving the GitHub issues section for bugs and feature requests. 
Please post questions at https://groups.google.com/forum/#!forum/loopbackjs. See https://github.com/strongloop/loopback/wiki/Questions for more details.

Hopefully someone can help you out in there!
