### ISSUE TITLE
Use ACL in non REST routes

### ISSUE THREAD

**Issue by mbouclas** [strongloop/loopback-example-access-control#68]
Is it possible to figure out the users roles in a standard express route? For example, one might want to have a route accessible only for certain roles. How would this work?

**Comment by richardpringle** [comment]
@mbouclas, this is a difficult question to answer. In short, no you can't. I have seen some instances where community members will implement some custom functionality though, they might have a better idea of how you could achieve something similar.

Try asking in one (or more) of the following locations:
- [Google Groups](https://groups.google.com/forum/#!forum/loopbackjs)
- [StackOverflow](http://stackoverflow.com/questions/tagged/loopbackjs+or+strongloop?sort=newest&pageSize=50)
- [Gitter](https://gitter.im/strongloop/loopback) (supported, but we prefer posting to Google Groups so others may benefit from the discussions)

We are also reserving GitHub issues for bug reports and feature requests so I will close this issue, but I am sure you will find a much better discussion in the aforementioned communities (also, hopefully a response won't take so long).

Good luck and happy coding!
