### ISSUE TITLE
Index.ejs not shown 

### ISSUE THREAD

**Issue by daslicht** [strongloop/loopback-example-access-control#69]
Hello,
When I navigate to / I just get : 
```
{
started: "2015-11-19T10:58:00.672Z",
uptime: 5.163
}
```

Any Idea why ?

I can open /projects without entering any credentials ?

Here is my code:
https://github.com/daslicht/loopback-example-access-control

**Comment by 0candy** [comment]
@daslicht You have to remove the /server/boot/root.js file

**Comment by 0candy** [comment]
@daslicht Hope the above resolved your issue, I am closing this for now. If you are still having issues, please feel free to reopen.

**Comment by daslicht** [comment]
I haven't  it again since then,  thank you for the reply
