### ISSUE TITLE
TypeError: app.models.User.login is not a function

### ISSUE THREAD

**Issue by dongmai** [strongloop/loopback-example-access-control#74]
Hi everyone, 

I catch this error after click login button.
Can someone figure it out?

Thanks.

**Comment by superkhau** [comment]
Did you extend the base user? https://github.com/strongloop/loopback-example-access-control/blob/master/common/models/user.json#L3

**Comment by dongmai** [comment]
Yes, that's reason. I forgot to extend 'PersistedModel'.

**Comment by superkhau** [comment]
@dongmai Cool, thanks for closing. ;)
