### ISSUE TITLE
loopback-example-access-control & MySQL

### ISSUE THREAD

**Issue by talpasco** [strongloop/loopback-example-access-control#75]
Running this example on memory DB, it runs perfectly.
But, using MySQL as data-source, produce the following error:

C:\loopback-example-access-control\node_modules\mysql\lib\protocol\Parser.js:77
throw err; // Rethrow non-MySQL errors
^
ValidationError: The user instance is not valid. Details: email is invalid (value: "john@doe.com"); username is invalid (value: "John").,ValidationError: The user instance is not valid. Details: email is invalid (value: "jane@doe.com"); username is invalid (value: "Jane").,ValidationError: The user instance is not valid. Details: email is invalid (value: "bob@projects.com"); username is invalid (value: "Bob").

I found out that if I modify the 'User' inside the 'model.config.json' to use the memory connector, like this:

> "user": {
>     "dataSource": "localdb",
>     "public": true
>   }

It runs smoothly. So the problem is in the User entity.

BTW, If it helps... I've forked this project and modified the files as described in here:
https://github.com/talpasco/loopback-example-access-control/commit/2339d45641705ad7f862f591a70ca5cd4187f75e

And the project...
https://github.com/talpasco/loopback-example-access-control

Thanks for all the help in this awesome project,
Tal

**Comment by talpasco** [comment]
I've forked this project and modified the files as described in here:
https://github.com/talpasco/loopback-example-access-control/commit/2339d45641705ad7f862f591a70ca5cd4187f75e

And the project...
https://github.com/talpasco/loopback-example-access-contro

**Comment by talpasco** [comment]
It seems like the problem has something to do with the relation between user and project.
If I remove the creation of the project, it would update the db (sample-models.js):

> users[0].projects.create({
      name: 'project1',
      balance: 100
    }, function(err, project) {
      if (err) throw err;

**Comment by talpasco** [comment]
So, the problem is that the ownerId property wasn't mentioned in the 'project.json' file. Just look at the following commit, that should do it:
https://github.com/talpasco/loopback-example-access-control/commit/6fa0e9ccbddd2fd469ce2fb39b2bdda520fb3c30

And this commit will provide the tutorial for the MySQL datasource:
https://github.com/talpasco/loopback-example-access-control/commit/2339d45641705ad7f862f591a70ca5cd4187f75e

**Comment by richardpringle** [comment]
@talpasco sorry about the delayed response... but you probably learned more by me not responding right away :wink:. 

I could go in and make this change but I think that you should get credit as a contributor! Do you want to submit a PR for the change in `project.json` file? 

I'll hold off on making the change until I hear back, but if you do want to Open a PR [here's a guide](https://github.com/strongloop/loopback/wiki/Contributing-code). Then make sure to mention me in a comment so I go and take a look right away!

Cheers

**Comment by talpasco** [comment]
Don't really know what happened, I'm pretty convinced it did work. But I'm getting the same error message right now. It seems I don't deserve any credit..

**Comment by herbat73** [comment]
My remark how to ajust code to mysql database.
1. Model name cannot be 'user' otherwise it creates table conflicts. My advice is name it to 'appuser'
2. On server/boot/autoMigrate.js you need to first create database stucture (automigrate) some like @talpasco wrote and wait a bit and latter load data to tables. I am using for that purpose Promise function with 5 sek delay.

My repo updated is here https://github.com/herbat73/loopback-example-access-control

**Comment by richardpringle** [comment]
@herbat73, you should PR your code. I'm not actually working on LoopBack anymore so I couldn't tell you if it would get merged or not, but it's not a bad idea to try.
