### ISSUE TITLE
role-resolver.js

### ISSUE THREAD

**Issue by victorhazbun87** [strongloop/loopback-example-access-control#89]
I'm registering and using a role: this are the scripts:

role-resolver.js 
https://gist.github.com/victorhazbun87/ecf28d78ca5eb926a16f64092492e60b

application-request-config.json
https://gist.github.com/victorhazbun87/445f9cf1d9bb0a408358abd109f2d7ca

When I make a request to: **GET /ApplicationRequestConfigs/{id}** It always return 200 with the resource, It seems to not care about the result:

return cb(null, count > 0); // if count is true or false it always return the resource in the response.

If false I expect to not return the object... and this is not happening.

Thanks.

**Comment by victorhazbun87** [comment]
**UPDATE:** After some research and testing, I found that I need to put the following config  into the acls additional to my custom role in order to make it work:

    {
      "accessType": "*",
      "principalType": "ROLE",
      "principalId": "$everyone",
      "permission": "DENY"
    }

**Comment by Amir-61** [comment]
Closing as the issue has been resolved
