### ISSUE TITLE
ACL for third-party login

### ISSUE THREAD

**Issue by saltukalakus** [strongloop/loopback-example-access-control#92]
There was a lot of confusion in ACL support with third-party login in this [ticket](https://github.com/strongloop/loopback-component-passport/issues/65).

Could you kindly provide a third-party login scenario usage in this example? It would help a lot.

**Comment by saikatharryc** [comment]
exactly, facing same issue here.
i'm using auth0,
though on first login i'm saving user info to our db. [Dont have password here]
and using this user model and id to create a role.
but its not working,
after this:
```
"acls": [
    {
      "accessType": "*",
      "principalType": "ROLE",
      "principalId": "$everyone",
      "permission": "DENY"
    }
  ],
```
its taking post , get and all the request. missed something?
