### ISSUE TITLE
request /api/projects returns "Error: Authorization Required" when use mongodb datasource

### ISSUE THREAD

**Issue by wangdandong** [strongloop/loopback-example-access-control#94]
### Bug or feature request

- [x ] Bug
- [ ] Feature request

### Explain
Use memory db is ok. But when use mongodb datasource, error occurred, returns "Error: Authorization Required".

### Additional information (Node.js version, LoopBack version, etc)
Node.js version: v4.7.2
"loopback-connector-mongodb": "^3.0.0"

**Comment by Nygma297** [comment]
Try this: Go to **_server/boot/authentication.js_** and comment the line where it says `server.enableAuth();` and rerun again.

**Comment by wangdandong** [comment]
@Nygma297 I need the ACL feature, so I can't comment `server.enableAuth();`.
Is there something wrong in my environment ?

**Comment by Nygma297** [comment]
Can you post the datasources.js file?

**Comment by wangdandong** [comment]
```
{
  "db": {
    "host": "localhost",
    "port": 0,
    "url": "",
    "database": "test",
    "password": "",
    "name": "mongodb",
    "user": "",
    "connector": "mongodb"
  }
}
```

Other function except ACL is working well.

**Comment by Nygma297** [comment]
Make it something like this :
`{
  "db": {
    "name": "db",
    "connector": "memory"
  },
  "mongoDs": {
    "host": "localhost",
    "port": 0,
    "url": "",
    "database": "test",
    "password": "",
    "name": "mongoDb",
    "user": "",
    "connector": "mongodb"
  }
}`

PS: Create a seperate datasource for mongo, I hope it works

**Comment by GregBuchberger** [comment]
Same issue. 

Mongo collections and data are created successfully.

Then, authentication works but authorization does not.

**datasources.json:**
{
    "db": {
        "name": "db",
        "connector": "memory"
    },
    "mongoDS": {
        "host": "localhost",
        "port": 0,
        "url": "",
        "database": "AccessTest",
        "password": "",
        "name": "mongoDS",
        "user": "",
        "connector": "mongodb"
    }
}

**package.json:**
{
  "name": "loopback-example-access-control",
  "version": "1.0.0",
  "main": "server/server.js",
  "scripts": {
    "pretest": "jshint .",
    "start": "node .",
    "test": "mocha test/*test.js"
  },
  "dependencies": {
    "bcrypt": "^1.0.2",
    "body-parser": "^1.10.1",
    "compression": "^1.0.3",
    "cors": "^2.8.1",
    "loopback": "^3.0.0",
    "loopback-boot": "^2.4.0",
    "loopback-connector-mongodb": "^3.0.1",
    "serve-favicon": "^2.0.1",
    "strong-error-handler": "^1.1.1",
    "supertest": "^1.1.0"
  },
  "optionalDependencies": {
    "loopback-component-explorer": "^2.1.0"
  },
  "devDependencies": {
    "jshint": "^2.5.6",
    "mocha": "^2.3.3"
  },
  "repository": {
    "type": "git",
    "url": "git://github.com/strongloop/loopback-example-access-control"
  },
  "license": "MIT"
}


Via explorer, generate and set access token using 'admin' role credentials.
Then request ... /api/projects and get authorization error

**Error log:**

Unhandled error for request GET /projects: Error: Authorization Required
    at /Users/dev/loopback-example-access-control/node_modules/loopback/lib/application.js:389:21
    at /Users/dev/loopback-example-access-control/node_modules/loopback/lib/model.js:353:7
    at /Users/dev/loopback-example-access-control/node_modules/loopback/common/models/acl.js:464:16
    at /Users/dev/loopback-example-access-control/node_modules/async/dist/async.js:3694:9
    at /Users/dev/loopback-example-access-control/node_modules/async/dist/async.js:359:16
    at iteratorCallback (/Users/dev/loopback-example-access-control/node_modules/async/dist/async.js:935:13)
    at /Users/dev/loopback-example-access-control/node_modules/async/dist/async.js:843:16
    at /Users/dev/loopback-example-access-control/node_modules/async/dist/async.js:3691:13
    at apply (/Users/dev/loopback-example-access-control/node_modules/async/dist/async.js:21:25)
    at /Users/dev/loopback-example-access-control/node_modules/async/dist/async.js:56:12
    at /Users/dev/loopback-example-access-control/node_modules/loopback/common/models/acl.js:449:17
    at /Users/dev/loopback-example-access-control/node_modules/loopback/common/models/role.js:390:23
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)


node v6.9.2

Whereas, the in-memory datasource works perfectly well.

Any insights would be appreciated.

**Comment by BuchyOne** [comment]
## Authorization issues when using mongo
Does not occur when using memory as datasource

Mongo collections and data are created successfully.
Then, authentication works but authorization does not.

### datasources.json:
{
"db": {
"name": "db",
"connector": "memory"
},
"mongoDS": {
"host": "localhost",
"port": 0,
"url": "",
"database": "AccessTest",
"password": "",
"name": "mongoDS",
"user": "",
"connector": "mongodb"
}
}

### package.json:
{
"name": "loopback-example-access-control",
"version": "1.0.0",
"main": "server/server.js",
"scripts": {
"pretest": "jshint .",
"start": "node .",
"test": "mocha test/*test.js"
},
"dependencies": {
"bcrypt": "^1.0.2",
"body-parser": "^1.10.1",
"compression": "^1.0.3",
"cors": "^2.8.1",
"loopback": "^3.0.0",
"loopback-boot": "^2.4.0",
"loopback-connector-mongodb": "^3.0.1",
"serve-favicon": "^2.0.1",
"strong-error-handler": "^1.1.1",
"supertest": "^1.1.0"
},
"optionalDependencies": {
"loopback-component-explorer": "^2.1.0"
},
"devDependencies": {
"jshint": "^2.5.6",
"mocha": "^2.3.3"
},
"repository": {
"type": "git",
"url": "git://github.com/strongloop/loopback-example-access-control"
},
"license": "MIT"
}

Via explorer, generate and set access token using 'admin' role credentials.
Then request ... /api/projects and get authorization error

### error log:

Unhandled error for request GET /projects: Error: Authorization Required
at /Users/dev/loopback-example-access-control/node_modules/loopback/lib/application.js:389:21
at /Users/dev/loopback-example-access-control/node_modules/loopback/lib/model.js:353:7
at /Users/dev/loopback-example-access-control/node_modules/loopback/common/models/acl.js:464:16
at /Users/dev/loopback-example-access-control/node_modules/async/dist/async.js:3694:9
at /Users/dev/loopback-example-access-control/node_modules/async/dist/async.js:359:16
at iteratorCallback (/Users/dev/loopback-example-access-control/node_modules/async/dist/async.js:935:13)
at /Users/dev/loopback-example-access-control/node_modules/async/dist/async.js:843:16
at /Users/dev/loopback-example-access-control/node_modules/async/dist/async.js:3691:13
at apply (/Users/dev/loopback-example-access-control/node_modules/async/dist/async.js:21:25)
at /Users/dev/loopback-example-access-control/node_modules/async/dist/async.js:56:12
at /Users/dev/loopback-example-access-control/node_modules/loopback/common/models/acl.js:449:17
at /Users/dev/loopback-example-access-control/node_modules/loopback/common/models/role.js:390:23
at _combinedTickCallback (internal/process/next_tick.js:67:7)
at process._tickCallback (internal/process/next_tick.js:98:9)


node v6.9.2

Whereas, the in-memory datasource works perfectly well.

Any insights would be appreciated.

**Comment by Nygma297** [comment]
@BuchyOne 

Try adding a **DataSourceJuggler** Npm Package Maybe that'd help. 
Here: https://www.npmjs.com/package/loopback-datasource-juggler

I Hope it works.

**Comment by BuchyOne** [comment]
@Nygma297 

No, it does not resolve the issue.

I will debug and if successful get back.

**Comment by BuchyOne** [comment]
Using DEBUG=loopback:connector:mongodb

it appears the request to the RoleMapping fails:

loopback:connector:mongodb all +5ms RoleMapping { where: 
   { roleId: 58b5f81ce60625467c762913,
     principalType: 'USER',
     principalId: '58b5f81ce60625467c762910' },
  limit: 1,
  offset: 0,
  skip: 0,
  order: [ 'id' ] } null []

Check this:
https://github.com/strongloop/loopback-connector-mongodb/issues/327

For now I am adding the v1.17.0 connector.

So, the dependencies in our package.json:

  "dependencies": {
        "bcrypt": "^1.0.2",
        "body-parser": "^1.10.1",
        "compression": "^1.0.3",
        "cors": "^2.8.1",
        "loopback": "^3.0.0",
        "loopback-boot": "^2.4.0",
        "loopback-connector-mongodb": "1.17.0",
        "mongodb": "^2.2.22",
        "serve-favicon": "^2.0.1",
        "strong-error-handler": "^1.1.1",
        "supertest": "^1.1.0"
    }

**Comment by BuchyOne** [comment]
@Nygma297 

This answer works, but will break production:
https://github.com/strongloop/loopback/issues/3121#issuecomment-278811202

This is a better answer
https://github.com/strongloop/loopback/issues/3121#issuecomment-280283743

This is the answer !
https://github.com/strongloop/loopback/issues/3121#issuecomment-280635105

**Comment by sminodonte** [comment]
same problem for me and not resolve with these solutions...

my model-config file is:

{
  "_meta": {
    "sources": [
      "loopback/common/models",
      "loopback/server/models",
      "../common/models",
      "./models"
    ]
  },
  "User": {
    "dataSource": "mongoDB",
    "public": false
  },
  "AccessToken": {
    "dataSource": "mongoDB",
    "public": false
  },
  "ACL": {
    "dataSource": "mongoDB",
    "public": false
  },
  "RoleMapping": {
    "dataSource": "mongoDB",
    "options": {
      "strictObjectIDCoercion": true
    },
    "public": false
  },
  "Role": {
    "dataSource": "mongoDB",
    "public": false
  },
  "Email": {
    "dataSource": "emailDs"
  },
  "user": {
    "dataSource": "mongoDB",
    "public": true,
    "options": {
      "emailVerificationRequired": true
    }
  }
}


do I made some error?

**Comment by sminodonte** [comment]
Any insights will be appreciated, thanks

**Comment by YSTomar** [comment]
I am also experiancing same problem, Any help will be appreciated

**Comment by BuchyOne** [comment]
@YSTomar @sminodonte 

If you scaffolded then it should be ok, otherwise you need the solution here :
[strongloop/loopback#3121 (comment)](https://github.com/strongloop/loopback/issues/3121#issuecomment-280635105)

If this does not work it could be because the example really only runs in memory. To run it in Mongo be aware that the hard coded simple ids e.g. 1, 2 ... in  the form /server/views/project.ejs  will not find your Mongo objectids.

So, you will need to edit form input values accordingly :

`<input type="hidden" name="id" value="1">`
to
`<input type="hidden" name="id" value="[the object id from mongo]">`

But, if you hack this, then you will need to edit the remote methods so that arg: id is a string not a number :

`Project.remoteMethod('donate', {
    accepts: [
      {arg: 'id', type: 'number'}`
to

`Project.remoteMethod('donate', {
    accepts: [
      {arg: 'id', type: 'string'}`

Perhaps this will  help you get going.

**Comment by emazzu** [comment]
I m the same problem !!!!

**Comment by quinnliu** [comment]
Nygma297's comment works for 

```
> node --version
v4.4.6
```
and 
```
    "loopback": "^3.0.0",
    "loopback-boot": "^2.6.5",
    "loopback-component-explorer": "^4.0.0",
    "loopback-connector-mysql": "^5.2.0",
```

**Comment by kuongknight** [comment]
The issue still exits, any help will be appreciated

**Comment by anupammaurya** [comment]
Same track, no solution found for this?

**Comment by felixia** [comment]
Am equally stuck with the same problem...any solution?

**Comment by wangdandong** [comment]
a solution, see https://github.com/strongloop/loopback-example-access-control/issues/94#issuecomment-283229447
> https://github.com/strongloop/loopback/issues/3121#issuecomment-280635105

**Comment by marcus-gomes-v** [comment]
Guys i keep with the problem, even adding options to every of my models.
```
 "options": {
      "strictObjectIDCoercion": true
    },
```
maybe i not understand exactly what i need to do.
i need just put the options on my models, or i need to change my role and role mapping model to use memoryDS ?
