### ISSUE TITLE
Readme 'Tutorial' links broken

### ISSUE THREAD

**Issue by lriggle-strib** [strongloop/loopback-example-access-control#95]
### Bug or feature request
- [x] Bug
- [ ] Feature request

### Description of feature (or steps to reproduce if bug)
Some links in your readme.md file are no longer working. The links for:

* Tutorial series - step 1
* Tutorial series - step 2
* Tutorial series - step 3

all lead to 404 pages.

**Comment by superkhau** [comment]
Would you like to submit a PR to fix it? @crandmck can give you a hand with regards to where in the links should point to.

**Comment by crandmck** [comment]
@lriggle-strib  

- Link to Getting Started should be https://loopback.io/doc/en/lb3/Getting-started-with-LoopBack.html (the URL redirects there, but might as well fix it).
- The other three links "Tutorial series - step 1/2/3" Should be replaced with one link to [Tutorials and examples](https://loopback.io/doc/en/lb3/Tutorials-and-examples.html).  We removed the https://github.com/strongloop/loopback-example repo, which is they're `404`.
